# Generated by Django 5.1.1 on 2024-10-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TourCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('image', models.FileField(max_length=200, upload_to='tour_category/')),
                ('status', models.BooleanField(default=False)),
                ('sale', models.SmallIntegerField(default=0)),
                ('city', models.SmallIntegerField(default=0)),
                ('place', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
